name: plantbot_care
description: A plant care robot control app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  flutter_svg: ^1.1.6
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.2
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  # flutter_reactive_ble: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tomato_disease_model.tflite
    - assets/images/tomato_logo.svg
    - assets/images/tomato_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/tomato_icon.png"
  remove_alpha_ios: true